// This file was generated by the SafeDIGenerateDependencyTree build tool plugin.
// Any modifications made to this file will be overwritten on subsequent builds.
// Please refrain from editing this file directly.

#if canImport(Core)
import Core
#endif
#if canImport(SafeDI)
import SafeDI
#endif
#if canImport(SearchUser)
import SearchUser
#endif
#if canImport(SwiftUI)
import SwiftUI
#endif
#if canImport(WebView)
import WebView
#endif

extension App {
    public init() {
        let gitHubUserRepository: any GitHubUserRepository = GitHubUserRepositoryImpl()
        func __safeDI_gitHubUserListViewBuilder() -> GitHubUserListView {
            let viewModel = GitHubUserListViewModel(gitHubUserRepository: gitHubUserRepository)
            return GitHubUserListView(viewModel: viewModel)
        }
        let gitHubUserListViewBuilder = Instantiator<GitHubUserListView>(__safeDI_gitHubUserListViewBuilder)
        self.init(gitHubUserRepository: gitHubUserRepository, gitHubUserListViewBuilder: gitHubUserListViewBuilder)
    }
}